[package]
name = "pallet-messages-rpc"
version = "1.11.0-rc1+polkadot1.1.0"
description = "A package that adds RPC to Messages pallet"
authors = ["Frequency"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"

[dependencies]
jsonrpsee = { workspace = true, features = ["client-core", "server", "macros"] }
# Frequency crates
pallet-messages-runtime-api = { default-features = false, path = "../runtime-api" }
common-primitives = { default-features = false, path = "../../../../common/primitives" }
common-helpers = { default-features = false, path = "../../../../common/helpers" }
# Substrate crates
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-runtime = { workspace = true }
frame-support = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "time", "parking_lot"] }
substrate-test-runtime-client = { workspace	= true }
sc-client-api = { workspace = true }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-runtime/std",
	'frame-support/std',
	"pallet-messages-runtime-api/std",
	'common-primitives/std',
	"common-helpers/std",
]
