[package]
name = "pallet-capacity-runtime-api"
version = "1.16.0-rc2+polkadotstable2412"
description = "A package that adds Runtime Api for the Capacity pallet"
authors = ["Frequency"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/frequency-chain/frequency/"
edition = "2021"


[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
sp-api = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
common-primitives = { path="../../../../common/primitives", default-features = false}

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "sp-api/std",
    "sp-runtime/std"
]

[lints]
workspace = true
