[package]
authors = ["Frequency"]
description = "Handles Utilities"
edition = "2021"
build = "build.rs"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = "handles-utils"
version = "1.7.4+polkadot0.9.42"
publish = false
repository = "https://github.com/libertyDSNP/frequency/"

[dependencies]
phf = { version = "0.11", default-features = false, features = ["macros"] }
oorandom = "11.1.3"
unicode-normalization = { version = "0.1.22", default-features = false }
twox-hash = { version = "1.6.3", default-features = false, features = ["digest_0_10"] }

[features]
default = ["std"]
std = []
