[package]
authors = ["Frequency"]
description = "Handles Utilities"
edition = "2021"
build = "build.rs"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = "handles-utils"
version = "1.15.0+polkadot1.13.0"
publish = false
repository = "https://github.com/frequency-chain/frequency/"

[dependencies]
phf = { workspace = true, features = ["macros"] }
oorandom = { workspace = true }
unicode-normalization = { workspace = true }
twox-hash = { workspace = true, features = ["digest_0_10"] }

[features]
default = ["std"]
std = []
