# Node Key Alice: `subkey inspect //Alice`
# Node Key Bob: `subkey inspect //Bob`
version: '3'
services:
  relay_alice:
    container_name: alice
    image: "parity/polkadot:v0.9.18"
    hostname: relay_alice
    ports:
      - "30334:30334" # p2p port
      - "9934:9933" # rpc port
      - "9945:9944" # ws port
    volumes:
      - type: bind
        source: ./res/rococo-local.json
        target: /chainspec.json
        read_only: true
    command: >
      --chain=/chainspec.json
      --node-key=e5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a
      --wasm-execution=compiled
      --execution=wasm
      --base-path=/data
      --port 30334
      --rpc-port 9933
      --ws-port 9944
      --rpc-external
      --rpc-cors all
      --ws-external
      --rpc-methods=Unsafe
      --alice
      --log="main,debug"

  relay_bob:
    container_name: bob
    image: "parity/polkadot:v0.9.18"
    hostname: relay_bob
    ports:
      - "30335:30335" # p2p port
      - "9935:9933" # rpc port
      - "9946:9944" # ws port
    volumes:
      - type: bind
        source: ./res/rococo-local.json
        target: /chainspec.json
        read_only: true
    command: >
      --chain=/chainspec.json
      --node-key=398f0c28f98885e046333d4a41c19cee4c37368a9832c6502f6cfd182e2aef89
      --base-path=/data
      --wasm-execution=compiled
      --execution=wasm
      --port 30335
      --rpc-port 9933
      --ws-port 9944
      --rpc-external
      --ws-external
      --rpc-cors all
      --rpc-methods=Unsafe
      --bob
      --log="main,info"

  collator_mrc:
    container_name: mrc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST_ALICE=relay_alice
      - HOST_BOB=relay_bob
      - ALICE_RPC_PORT=9933
      - BOB_RPC_PORT=9933
    ports:
      - "30333:30333" # p2p port
      - "9933:9933" # rpc port
      - "9944:9944" # ws port
    depends_on:
      - relay_alice
      - relay_bob
