[toolchain]
# If you update this, ALSO update the ci-base-image on branch `ci/ci-base-image`
# and update the CI base image version everywhere
channel = "1.90"
components = [ "clippy", "rust-docs", "rustfmt"]
targets = [ "wasm32v1-none" ]
profile = "minimal"
