name: 'Set Swap Space'
description: 'Add moar swap'
branding:
  icon: 'crop'
  color: 'orange'
inputs:
  swap-size-gb:
    description: 'Swap space to create, in Gigabytes.'
    required: false
    default: '10'
runs:
  using: "composite"
  steps:
    - name: Swap space report before modification
      shell: bash
      run: |
        echo "Memory and swap:"
        free -h
        echo
        swapon --show
        echo
    - name: Set Swap
      shell: bash
      run: |
        export SWAP_FILE="/tmp/swap"
        sudo swapoff $SWAP_FILE || true
        sudo rm -f $SWAP_FILE
        sudo fallocate -l ${{ inputs.swap-size-gb }}G $SWAP_FILE
        sudo chmod 600 $SWAP_FILE
        sudo mkswap $SWAP_FILE
        sudo swapon $SWAP_FILE

    - name: Swap space report after modification
      shell: bash
      run: |
        echo "Memory and swap:"
        free -h
        echo
        swapon --show
        echo
