[package]
name = 'pallet-graph-runtime-api'
version = '0.1.0'
description = 'A package that adds Runtime Api for Graph pallet'
authors = ['Frequency Team']
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"


[dependencies]
codec = {package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive"]}

# Substrate
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.28" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.28" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.28" }

# Frequency related dependencies
common-primitives = {default-features = false, path = "../../../../common/primitives" }


[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"frame-support/std",
	'common-primitives/std'
]
