[package]
authors = ["MRC Team"]
description = "Pallet for schema registry implementation"
edition = "2021"
homepage = "https://unfinishedlabs.io/"
license = "Apache-2.0"
name = "schema-rpc"
publish = false
repository = "https://github.com/libertyDSNP/mrc/"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2" }
jsonrpc-core = "18.0"
jsonrpc-core-client = "18.0"
jsonrpc-derive = "18.0"
serde = { version = "1.0", features = ["derive"], optional = true }

schema-runtime-api = { version = "0.1.0", path = "../runtime-api", default-features = false }
common-primitives = { version = "0.1.0", path = '../../../../common/primitives' }
common-helpers = { version = "0.1.0", path = '../../../../common/helpers' }

# Substrate
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18", optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-core/std",
	"frame-support/std",
	"sp-std/std",
	"common-primitives/std",
    "common-helpers/std",
]
