[package]
name = "pallet-msa-rpc"
version = "0.9.30"
description = "A package that adds RPC to Msa pallet"
authors = ["Frequency"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5" }
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] }
rayon = "1.5.3"
did-parser = { git = "https://github.com/davebryson/did-parser", default-features = false, commit = "0774161e399d96c38100b8bfbbb26b110a36bbaf" }
nom = "7.1.1"

# unfinished
pallet-msa-runtime-api = { default-features = false, path = "../runtime-api" }
common-primitives = { default-features = false, path = "../../../../common/primitives" }
common-helpers = { default-features = false, path = "../../../../common/helpers" }
# Substrate packages
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }

[features]
default = ["std"]
std = [
	'codec/std',
	"sp-api/std",
	"sp-runtime/std",
	"pallet-msa-runtime-api/std",
	'common-primitives/std',
]
