[package]
name = "pallet-msa-rpc"
version = "1.5.2+polkadot0.9.36"
description = "A package that adds RPC to Msa pallet"
authors = ["Frequency"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
rayon = "1.5.3"
# Frequency crates
pallet-msa-runtime-api = { default-features = false, path = "../runtime-api" }
common-primitives = { default-features = false, path = "../../../../common/primitives" }
common-helpers = { default-features = false, path = "../../../../common/helpers" }
# Substrate crates
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }

[dev-dependencies]
tokio = { version = "1.24.1", features = ["macros", "time", "parking_lot"] }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }

[features]
default = ["std"]
std = [
	'codec/std',
	"sp-api/std",
	"sp-runtime/std",
	"pallet-msa-runtime-api/std",
	'common-primitives/std',
	"common-helpers/std",
]
