[package]
name = "pallet-handles-rpc"
version = "1.16.0+polkadotstable2503"
description = "A package that adds RPC to Handles pallet"
authors = ["Frequency"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/frequency-chain/frequency/"
edition = "2021"

[dependencies]
jsonrpsee = { workspace = true, features = ["client-core", "server", "macros"] }
rayon = { workspace = true }
# Frequency crates
pallet-handles-runtime-api = { default-features = false, path = "../runtime-api" }
common-primitives = { default-features = false, path = "../../../../common/primitives" }
common-helpers = { default-features = false, path = "../../../../common/helpers" }
# Substrate crates
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-runtime = { workspace = true }
frame-support = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "time", "parking_lot"] }
sc-client-api = { workspace = true }

[features]
default = ["std"]
std = [
  'sp-api/std',
  'sp-runtime/std',
  "frame-support/std",
  'pallet-handles-runtime-api/std',
  'common-primitives/std',
  'common-helpers/std',
]

[lints]
workspace = true
