[package]
authors = ["Frequency"]
edition = '2021'
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = 'westend-system-emulated-network'
publish = false
version = "0.0.0"

[dependencies]
asset-hub-westend-emulated-chain = { workspace = true }
emulated-integration-tests-common = { workspace = true }
westend-emulated-chain = { workspace = true }
frequency-emulated-chain = { path = "../../chains/frequency-westend" }
polkadot-runtime-parachains = { workspace = true }
