# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check Polkadot Releases
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # midnight (UTC)
env:
  REPO_URL: https://api.github.com/repos/paritytech/polkadot-sdk
  TRACKING_GIT_BRANCH: ci/latest-polkadot-full-release
  RELEASE_TRACK_FILENAME: .github/.latest-polkadot-full-release.txt

# Set default permissions as restrictive
permissions:
  contents: write

jobs:
  record-polkadot-latest-release-version:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp
        run: date
      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          ref: ${{env.TRACKING_GIT_BRANCH}}
          # While you can write to a branch without it, it will not trigger the workflow
          token: ${{secrets.GHA_RECORD_POLKADOT_RELEASE}}
      - name: Print Recorded Latest Polkadot Release
        run: |
          echo "Recorded Polkadot Latest Full Release:"
          echo "--------------------------------------"
          cat ${{env.RELEASE_TRACK_FILENAME}}
      - name: Fetch Latest Release Version
        run: |
          curl -sL $REPO_URL/releases/latest | \
          jq -r ".tag_name" > ${{env.RELEASE_TRACK_FILENAME}}
          echo "Fetched Polkadot Latest Full Release:"
          echo "-------------------------------------"
          cat ${{env.RELEASE_TRACK_FILENAME}}
      - name: Commit Latest Release Version
        id: commit-updated-release
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
        with:
          commit_message: "Record new Polkadot release version"
          commit_user_name: Frequency CI [bot]
          commit_user_email: do-not-reply@users.noreply.github.com
          commit_author: Frequency CI [bot] <do-not-reply@users.noreply.github.com>
