# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Create Issue for Dependabot Alert PR
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, reopened]
    paths:
      - .github/workflows
jobs:
  create-issue:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PR_TITLE: ${{github.event.pull_request.title}}
      PR_NUMBER: ${{github.event.pull_request.number}}
      PR_URL: ${{github.event.pull_request.url}}
    steps:
      - name: Check Out Repo
        if: github.event.pull_request.user.login  == 'dependabot[bot]'
        uses: actions/checkout@v4
      - name: Create GitHub Issue
        if: github.event.pull_request.user.login  == 'dependabot[bot]'
        id: create-issue
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
        with:
          filename: .github/issues/dependabot-alert.template.md
      - name: Link PR to New Issue
        if: github.event.pull_request.user.login  == 'dependabot[bot]'
        env:
          PR_BODY_FILENAME: /tmp/current-pr-body-${{github.run_id}}.txt
        run: |
          gh pr view ${{env.PR_URL}} --json body --jq '.body' > ${{env.PR_BODY_FILENAME}}
          echo -e "\n\nResolves: #${{steps.create-issue.outputs.number}}" >> ${{env.PR_BODY_FILENAME}}
          gh pr edit ${{env.PR_URL}} --body-file ${{env.PR_BODY_FILENAME}}
          rm ${{env.PR_BODY_FILENAME}}
