on:
  push:
    branches: [main]
  pull_request:

name: Build Main
jobs:
  build_prep:
    name: build-prep
    runs-on: 'ubuntu-latest'
    outputs:
      matrix: ${{ steps.set-build-param.outputs.matrix }}
    steps:
      # Required as the JSON input file needs to be read
      - uses: actions/checkout@v3
      - id: set-build-param
        uses: JoshuaTheMiller/conditional-build-matrix@b9af2b1b137d7bd7818c1233ef830b326809a7cc
        with:
          inputFile: '.github/workflows/build-params.json'
          # we run build-node on every workflow but build-runtime only on pushes to branches
          filter: '[?run_on_event==`any` || run_on_event==`${{ github.event_name }}`]'
  build:
    needs: build_prep
    strategy:
      matrix: ${{fromJson(needs.build_prep.outputs.matrix)}}
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    env:
      RUST_TOOLCHAIN: ${{ matrix.rust_toolchain }}
    steps:
      - name: Free space on Ubuntu
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          echo "Pre cleanup"
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "Post cleanup"
          df -h
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          default: true
      - if: matrix.target == 'build-runtime' || matrix.target == 'build-runtime-rococo'
        uses: Swatinem/rust-cache@v1
        with: # cache the runtime target instead of root target for build-runtime
          working-directory: './runtime'
          target-dir: './target/frequency'
      - if: matrix.target == 'build-node'
        uses: Swatinem/rust-cache@v1
      - name: ${{ matrix.target }}
        run: ./ci/build.sh
        env:
          TARGET: ${{ matrix.target }}
          RUST_TOOLCHAIN: ${{ matrix.rust_toolchain }}
          PACKAGE: ${{matrix.package}}
          RUNTIME_DIR: ${{ matrix.dir }}
      - name: Create tarball  of deterministic wasm from srtool ðŸ“¦
        if: matrix.target == 'build-runtime' && matrix.package == 'frequency-runtime'
        run: tar -cvf frequency_wasm.tar ./runtime/frequency/target/srtool/release/wbuild/frequency-runtime
      - name: Upload frequency deterministic wasm to artifacts ðŸ“¦
        if: matrix.target == 'build-runtime' && matrix.package == 'frequency-runtime'
        uses: actions/upload-artifact@v3
        with:
          name: frequency_wasm_srtool-${{ github.sha }}
          path: frequency_wasm.tar
      - name: Create tarball  of deterministic wasm from srtool for rococoðŸ“¦
        if: matrix.target == 'build-runtime' && matrix.package == 'frequency-rococo-runtime'
        run: tar -cvf frequency_wasm_rococo.tar ./runtime/frequency-rococo/target/srtool/release/wbuild/frequency-rococo-runtime
      - name: Upload frequency deterministic wasm to artifacts for rococo ðŸ“¦
        if: matrix.target == 'build-runtime' && matrix.package == 'frequency-rococo-runtime'
        uses: actions/upload-artifact@v3
        with:
          name: frequency_wasm_srtool_rococo-${{ github.sha }}
          path: frequency_wasm_rococo.tar
      - name: Build Frequency related specs and wasm ðŸ“
        if: matrix.target == 'build-node'
        run: ./scripts/generate_specs.sh 2000 true
      - name: Create tarball  of specs and wasm ðŸ“¦
        if: matrix.target == 'build-node'
        run: tar -cvf frequency_specs.tar ./res/genesis
      - name: Upload frequency spec and wasm artifacts ðŸ“¦
        if: matrix.target == 'build-node'
        uses: actions/upload-artifact@v3
        with:
          name: frequency_rococo_2000_specs-${{ github.sha }}
          path: frequency_specs.tar
      - name: Set up QEMU
        if: matrix.target == 'build-node'
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: matrix.target == 'build-node'
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: matrix.target == 'build-node'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the tag name
        if: matrix.target == 'build-node'
        run: |
          date_tag=$(date +'%Y%m%d-%H%M')
          echo ${date_tag}
          echo "TAG=${date_tag}" >> $GITHUB_ENV
      - name: Build and push dsnp/frequency
        if: matrix.target == 'build-node'
        id: docker_build_frequency
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile
          tags: |
            dsnp/frequency:${{ env.TAG }}
            dsnp/frequency:latest
