# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# This workflow is used only when a development version of CI base image needs to be built.
name: Publish Dev CI Base Image
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push:
    branches:
      - disabled-as-this-branch-does-not-exist
      - 779-build-arm-binaries-and-containers-for-linux-and-macos
      # - 1639-upgrade-to-polkadot-release-v100
env:
  BIN_DIR: target/release

jobs:
  publish-ci-base-image:
    name: Publish CI Base Image
    env:
      # IMAGE_NAME: ci-base-image-dind
      IMAGE_NAME: ci-base-image
      IMAGE_VERSION: 1.2.0
      BRANCH_NAME: ${{github.ref_name}}
    runs-on: macos-14
    steps:
      - name: Install and Start Docker
        run: |
          brew install colima
          brew install --cask docker
          # open -a /Applications/Docker.app --args --unattended --accept-license
          colima start

      - name: Check Docker Daemon
        run: |
          docker --version
          cat /var/log/docker.log || echo "Docker log not found"
          ps aux | grep Docker

          # Make sure Docker Daemon is running
          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
          count=0
          while ! /Applications/Docker.app/Contents/Resources/bin/docker info >/dev/null 2>&1; do
            sleep 1
            echo -n "."
            count=$((count + 1))
            if [ $count -gt 600 ]; then
              echo "\cDocker failed to start"
              exit 1
            fi
          done 

      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "amd64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get Rust Version
        id: rust_version
        run: |
          echo "::set-output name=RUST_VERSION::$(rustc --version)"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Sanitize repo owner slug
        uses: actions/github-script@v7
        id: repo_slug
        with:
          result-encoding: string
          script: return `ghcr.io/${context.repo.owner.toLowerCase()}/${context.repo.repo.toLowerCase()}`
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: tools/ci/docker
          platforms: linux/amd64,linux/arm64
          push: true
          file: tools/ci/docker/ci-base-image.dockerfile
          tags: |
            ${{steps.repo_slug.outputs.result}}/${{env.IMAGE_NAME}}:${{env.BRANCH_NAME}}
          build-args: |
            IMAGE_VERSION=${{env.IMAGE_VERSION}}
            RUST_VERSION=${{steps.rust_version.outputs.RUST_VERSION}}
